
trigger:
- main

pool:
  name: dev
  demands:
    - Agent.Name -equals omkaragent




steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'omkarsc'
    KeyVaultName: 'omkarkeyvault234'
    SecretsFilter: '*'
    RunAsPreJob: true
- script: 
   echo $(dbpassword)

   


  

  


